import { GoogleGenAI } from "@google/genai";

const client = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

export async function generateFrame(
  prompt: string,
  referenceImageBytes?: Buffer,
  aspectRatio: string = "16:9"
): Promise<{ imageBytes: Buffer; mimeType: string; modelText?: string }> {
  const fullPrompt = prompt;

  const contents: Array<
    | string
    | { inlineData: { data: string; mimeType: string } }
  > = [];

  if (referenceImageBytes) {
    contents.push({
      inlineData: {
        data: referenceImageBytes.toString("base64"),
        mimeType: "image/png",
      },
    });
  }
  contents.push(fullPrompt);

  const response = await client.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents,
    config: {
      responseModalities: ["IMAGE", "TEXT"],
      imageConfig: {
        aspectRatio: aspectRatio as "16:9" | "9:16" | "1:1" | "3:4" | "4:3",
      },
    },
  });

  let modelText: string | undefined;
  let imageBytes: Buffer | undefined;
  let mimeType = "image/png";

  const parts = response.candidates?.[0]?.content?.parts ?? [];
  for (const part of parts) {
    if (part.inlineData) {
      imageBytes = Buffer.from(part.inlineData.data!, "base64");
      mimeType = part.inlineData.mimeType || "image/png";
    } else if (part.text) {
      modelText = part.text;
    }
  }

  if (!imageBytes) {
    throw new Error("No image generated by Gemini");
  }

  return { imageBytes, mimeType, modelText };
}
